### ISSUE TITLE
Menu Bar : Instert Direct Link to wikimedia.de

### ISSUE THREAD

**Issue by samu-wmde** [wmde/software.wikimedia.de#12]
It would be great when we could connect the website with wikimedia.de so that people which are more interest in background information can easy find them. 

Could we add Wikimedia Deutschland e.V. (link: wikimedia.de) in the toolbar ?

**Comment by JeroenDeDauw** [comment]
I was also wondering about this. We have several places in various text where we mention WMDE, where we could link to the site. Or alternatively to a page on the SWE site with a short blurb about WMDE and then a button/link to the other site.

Not sure about placing a link in the menu bar, since this seems to just be for things on the site itself. As a user I'd be rather surprised if a link there went to another site. Once we did https://github.com/wmde/software.wikimedia.de/issues/13 there will be a text with WMDE on the main page, we could link that to the external site. Would that be fine with you?

**Comment by samu-wmde** [comment]
The problem we have is that technically software.wikimedia.de is a subpage of wikimedia.de and wikimedia.de is not in English. So we can't create a new page for wikimedia.de but need to provide some kind of information. What we can do is explaining more about Wikimedia Deutschland e.V. in engl. and link to the website (wikimedia.de) + hint (only in german)

**Comment by JeroenDeDauw** [comment]
I don't understand what you are saying. Even so I get the impression it does not answer my question.

**Comment by JeroenDeDauw** [comment]
Please reopen if still relevant
