### ISSUE TITLE
Home Projects Wikidata-Contribute link wrong

### ISSUE THREAD

**Issue by jdittrich** [wmde/software.wikimedia.de#30]
A user who looks up software.wikimedia would probably be interested in software. However, the Wikidata "Contribute" link on https://software.wikimedia.de/projects leads to [edit/contribute to Wikidata-data page](https://www.wikidata.org/wiki/Wikidata:Contribute).

Sadly, I did not find a good place to link to for "contribute code to Wikidata". Wikiba.se seems not to have a section for that, https://www.mediawiki.org/wiki/Wikibase just is a branching site, https://www.mediawiki.org/wiki/Wikibase/Programmer's_guide_to_Wikibase seems best, but is info overload.

**Comment by JeroenDeDauw** [comment]
Yeah... This is a remnant of the olds sites content. I was thinking of having a more Wikibase focused thing on this page that mentions Wikidata, rather than the other way round. And perhaps have a wikidata focused thing elsewhere (not in the technical project list). Proposals on how to handle that welcome.

**Comment by manicki** [comment]
Closing as this site is being shut down.
