### ISSUE TITLE
Linking team members to the other teams 

### ISSUE THREAD

**Issue by jdittrich** [wmde/software.wikimedia.de#50]
**Story:** As a visitor I want to see who is in the teams. When deal with Wikidata and have a problem with the Interface, I would talk to Jan, but they are not on the Wikidata  team directly. 

**Solution:** We might just provide links to these people as the last line in the team member listing.

**Comment by JeroenDeDauw** [comment]
If I understand correctly the story would be better phrased as "When I have a specific problem for a project, I want to be able to find out who at WMDE SWE to talk to. (Example: If I have a UX problem with Wikidata I want to be able to find that the responsible person is Jan)". Is that what you are after?

Given this is about projects, I would find it more natural to list contact people on the projects page. And where possible, link to a more detailed offsite page. For instance I assume Wikidata has such a page, and in case of Wikidata there will be non WMDE employees on it (ie site admins and whatnot).

Listing this on the projects page might not be as visible as you want, in which case I can see how also putting links on the department page might help. That approach concerns me though, since I think it's bad to equate teams with projects. This is because a team can work on multiple projects. Perhaps those can be listed, which would make that clear, though I'm not sure how much value there is in that.

Writing this made me think of a related usecase: "I want people to see which things I am responsible for or can be contacted about". To tackle that I think it's best to extend the individual peoples sections in some form. (Which can be done together with mentioning people on the projects page.)

**Comment by jdittrich** [comment]
Thanks for the feedback!

> For instance I assume Wikidata has such a page, and in case of Wikidata there will be non WMDE employees on it (ie site admins and whatnot).

I think we don't have such a page and léa suggested to link here.

> "When I have a specific problem for a project, I want to be able to find out who at WMDE SWE to talk to. (Example: If I have a UX problem with Wikidata I want to be able to find that the responsible person is Jan)"

Nice story (and more clear than  my initial one). It is not what Lea and me had in mind I think. It was more "I talked to Jan on Wiki and I want to see what he does at Wikidata", but currently it is "He does not seem to have to do anything with it, since he is not in the team", thus the suggestion to provide a link.

**Comment by jdittrich** [comment]
Linking possibly looking like: 

![image](https://user-images.githubusercontent.com/3416487/27729508-723d5ed4-5d86-11e7-99d2-ac590fd1a073.png)

**Comment by jdittrich** [comment]
@jsoftwareengineering, could you make a pull request for above suggestion with the Text

"The Wikidata Team is supported by <a href=#>Jens</a> for <em>Data Partnerships</em> and <a href=#> Jan</a> and <a href=#>Charlie</a> for <em>User Experience Research and Design</em>", linking the names Jens, Charlie and Jan to the "Department wide" headline (which would need an own id for it)

**Comment by jsoftwareengineering** [comment]
@jdittrich Should "Technical Wishes" then also link to Jan and Charlie?

**Comment by jdittrich** [comment]
Good point. Yes, they should.

**Comment by JeroenDeDauw** [comment]
Is this done?

**Comment by jdittrich** [comment]
needs final OK…

**Comment by manicki** [comment]
Closing as this site is being shut down.
